
version: 2


references:
  triggerable-by-tag: &triggerable-by-tag
    tags:
      only: /^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta)\.\d+)?$/

  default_container_config: &default_container_config
    working_directory: ~/project
    docker:
      - image: circleci/node:8.10.0
        environment:
          DATABASE_URL: postgres://c4_admin:testpw@localhost:5432/c4test
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_DB: c4test
          POSTGRES_USER: c4_admin

  npm_cache_key: &npm_cache_key
    v2-dependency-npm-{{ checksum "package-lock.json" }}

  restore_node_dependencies: &restore_node_dependencies
    restore_cache:
      keys:
        - *npm_cache_key

  cache_node_dependencies: &cache_node_dependencies
    save_cache:
      key: *npm_cache_key
      paths:
        - "node_modules"

  workspace_root: &workspace_root
    ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  install:
    <<: *default_container_config
    steps:
      - checkout

      - *restore_node_dependencies
      - run: echo 'export PATH=./node_modules/.bin:$PATH' >> $BASH_ENV
      - run: npm install --unsafe-perm
      - run: snyk test

      - *cache_node_dependencies

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .
  test:
    <<: *default_container_config
    steps:
      - run: echo 'export PATH=./node_modules/.bin:$PATH' >> $BASH_ENV
      - run: npm install --unsafe-perm
      - run: npm run init
      - run: npm run test
      
  release:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/project/.npmrc
      - run: npm version --no-git-tag-version ${CIRCLE_TAG} && npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install:
          filters:
            <<: *triggerable-by-tag
      - test:
          requires:
            - install
          filters:
            <<: *triggerable-by-tag
      - release:
          requires:
            - install
            - test
          filters:
            <<: *triggerable-by-tag
            branches:
              ignore: /.*/
